### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by mg901** [marcello3d/polyfill.js#1]
Good day! Please tell me how I can connect polyfill.js
Using es6 modules?
`
import polyfill from 'polyfill';
`
When I try to connect polyfill.js, webpack generates an error.

`
ERROR in ./~/polyfill/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/mg901/Desktop/starter/node_modules/polyfill'
 @ ./~/polyfill/index.js 1:9-22
 @ ./_src/pages/index/index.js
`

**Comment by marcello3d** [comment]
You probably want a different project, this hasn't been touched in 4 years.
